# Generated by Django 4.2.5 on 2024-01-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp2_form', '0002_movieinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
