# Generated by Django 4.2.5 on 2024-01-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp2_form', '0003_alter_movieinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='image',
            field=models.FileField(default='/home/hp/Downloads/brain_05.png', upload_to=''),
        ),
    ]
